# spring:
#   application:
#     name: AppProdutos

#   h2:
#     console:
#       enabled: true
#       path: /h2-console

#   jpa:
#     database-platform: org.hibernate.dialect.H2Dialect
#     show-sql: true
#     hibernate:
#       ddl-auto: update

#   datasource:
#     url: jdbc:h2:mem:produtosdb
#     username: sa
#     password:

# Tomei a liberdade de trocar para PostgreSQL por ter mais familiaridade com ele.

spring:
  application:
    name: AppProdutos

  datasource:
    url: jdbc:postgresql://localhost:5432/appprodutos
    username: postgres
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
